### ISSUE TITLE
Can we see some screenshots of how the UI looks?

### ISSUE THREAD

**Issue by sumnerboy12** [kjk2010/AmpliPi-POE-Touchscreen-Keypad#2]
This looks really cool - my AmpliPi is currently on-route and I am very keen to get some wall mounted UIs - could you post some screenshots of what the UI looks like?

Looking forward to the first release!!

**Comment by kjk2010** [comment]
I've updated the readme file and uploaded some images. I'll take more picture and a video once I finish the 3D mount and start mounting the screens on to a wall.
https://github.com/kjk2010/AmpliPi-POE-Touchscreen

Side note, I tried purchasing more ESP32-POE devices and received notification that they won't be delivered until November next year... I don't know if this is true for all vendors, but I might need to port this over to a standard ESP32 without POE.

Thanks for your interest!

**Comment by sumnerboy12** [comment]
Nice one - thanks for adding those - looks really good!
